name = "hotels-p0-cloudflare"
type = "webpack"
account_id = "bb7db66d1187d912e43abc3a907caabc"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
